Repository labscanvas/labscanvas.github.io, pull requests merged in 2025-01, with the labels that each got.

#1 Development - Setting up the Basic Folder Structure
  README.md
  src/components/index.js
  src/pages/index.js
  src/static/style.css
Labels: Development

#9 Development - Creating Projects section
  src/components/Projects/Projects.jsx
  src/components/Projects/index.js
  src/components/index.js
  src/static/style.css
Labels: Development

#10 Bugfix - Fixing the path for NavBar in Banner Section
  src/components/Banner/Banner.jsx
Labels: bug

#13 Deployment - Final Deployment
  public/404.html
  public/404/index.html
  public/_gatsby/slices/_gatsby-scripts-1.html
  public/app-97bba47f6f18e0ffa5b1.js
  public/app-97bba47f6f18e0ffa5b1.js.LICENSE.txt
  public/app-97bba47f6f18e0ffa5b1.js.map
  public/chunk-map.json
  public/component---src-pages-404-js-e60783d7b2df3e6db618.js
  public/component---src-pages-404-js-e60783d7b2df3e6db618.js.map
  public/component---src-pages-index-js-18dd86ba84a5ee95b597.js
  public/component---src-pages-index-js-18dd86ba84a5ee95b597.js.map
  public/framework-8febf478d77f48439dd0.js
  public/framework-8febf478d77f48439dd0.js.LICENSE.txt
  public/framework-8febf478d77f48439dd0.js.map
  public/index.html
  public/page-data/404.html/page-data.json
  public/page-data/404/page-data.json
  public/page-data/app-data.json
  public/page-data/index/page-data.json
  public/styles.876b837156273b398440.css
  public/webpack-runtime-a0ebf55b254d750ee27b.js
  public/webpack-runtime-a0ebf55b254d750ee27b.js.map
  public/webpack.stats.json
  public/~partytown/debug/partytown-atomics.js
  public/~partytown/debug/partytown-media.js
  public/~partytown/debug/partytown-sandbox-sw.js
  public/~partytown/debug/partytown-sw.js
  public/~partytown/debug/partytown-ww-atomics.js
  public/~partytown/debug/partytown-ww-sw.js
  public/~partytown/debug/partytown.js
  public/~partytown/partytown-atomics.js
  public/~partytown/partytown-media.js
  public/~partytown/partytown-sw.js
  public/~partytown/partytown.js
Labels: Deployment
